// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// univLogReg
std::vector<double> univLogReg(std::vector<double> weights, Eigen::Map<Eigen::MatrixXd>& data, int column);
RcppExport SEXP adaboost615_univLogReg(SEXP weightsSEXP, SEXP dataSEXP, SEXP columnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type column(columnSEXP);
    rcpp_result_gen = Rcpp::wrap(univLogReg(weights, data, column));
    return rcpp_result_gen;
END_RCPP
}
// adaboost
NumericMatrix adaboost(Eigen::Map<Eigen::MatrixXd>& data);
RcppExport SEXP adaboost615_adaboost(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(adaboost(data));
    return rcpp_result_gen;
END_RCPP
}
// predictAda615
NumericVector predictAda615(NumericMatrix test, NumericMatrix train_results);
RcppExport SEXP adaboost615_predictAda615(SEXP testSEXP, SEXP train_resultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type test(testSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type train_results(train_resultsSEXP);
    rcpp_result_gen = Rcpp::wrap(predictAda615(test, train_results));
    return rcpp_result_gen;
END_RCPP
}
