# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

univLogReg <- function(weights, data, column) {
    .Call('adaboost615_univLogReg', PACKAGE = 'adaboost615', weights, data, column)
}

adaboost <- function(data) {
    .Call('adaboost615_adaboost', PACKAGE = 'adaboost615', data)
}

predictAda615 <- function(test, train_results) {
    .Call('adaboost615_predictAda615', PACKAGE = 'adaboost615', test, train_results)
}

